name: Build UI
on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
   runs-on: ubuntu-latest
   steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - run: bun install
        working-directory: src/nui
      - run: bun run build
        working-directory: src/nui

      - name: Commit changes
        run: |
          git config --global user.name "Miguel Facca"
          git config --global user.email "miguelfacca@outlook.com"
          git add -A
          git commit -m "📦 build ui" || true
          git push
