name: Build e Commit Dist

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar o Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Instalar dependências
        run: |
          cd src/nui
          bun install

      - name: Rodar build
        run: |
          cd src/nui
          bun run build

      - name: Commitar dist/
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add src/nui/dist
          git commit -m "Build✅"
          git push
        continue-on-error: true
 
