name: Build e Commit Dist

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar o Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Instalar dependências
        working-directory: ./src/nui
        run: |
          bun install

      - name: Rodar build
        working-directory: ./src/nui
        run: |
          bun run build

      - name: Commitar dist/
        run: |
          git config --local user.email "79928127+miguel-facca@users.noreply.github.com"
          git config --local user.name "Miguel Facca"
          git add -A
          git commit -m "Build✅"
          git push
        continue-on-error: true
 
